@startuml Entity Interpolation Animation - Sequence

participant "Client A" as ClientA
participant Server
participant "Client B" as ClientB

note over ClientA: p1 (0, 0)
/ note over Server: p1 (0, 0)
/ note over ClientB: p1 (0, 0)

ClientA -> Server: input: move-forward (id: 1)
note over ClientA: Begin movement animation

note over ClientA: Finish movement animation
/ note over Server: Update Game Model\nSimulate move-forward

note over ClientA #SkyBlue: p1 (0, 1)
/ note over Server #SkyBlue: p1 (0, 1)

ClientA -> Server: input: move-forward (id: 2)
note over ClientA: Begin movement animation

Server -> ClientA: update: game-state (ack id: 1)
Server -> ClientB: update: game-state

note over ClientA: Finish movement animation
/ note over Server: Update Game Model\nSimulate move-forward

note over ClientA #SkyBlue: p1 (0, 2)
/ note over Server #SkyBlue: p1 (0, 2)

Server -> ClientA: update: game-state (ack id: 2)
Server -> ClientB: update: game-state

note over ClientB: Begin movement animation
note over ClientB: Finish movement animation
note over ClientB #SkyBlue: p1 (0, 1)

@enduml
