@startuml Basic Network - Timing

concise "Client" as Client
concise "Server" as Server

@Client
0 is update
+10 is update
Client -> Server@+12 : input(move-forward)
+10 is update
+10 is update
+10 is update
+10 is update
+10 is update
+10 is update
+10 is update
+10 is update
+10 is update
+10 is update
Client@0 <-> @90 : p1 (0, 0)
Client@90 <-> @120 : p1 (0, 1)

@Server
0 is update
+20 is update
+20 is update
+20 is update
Server -> Client@+12 : update(game-state)
+20 is update
+20 is update
Server@0 <-> @60 : p1 (0, 0)
Server@60 <-> @120 : p1 (0, 1)

@enduml
